In [7]:
import torch
torch.__version__


'2.1.2+cu121'

In [8]:
import torch

# Creating a tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshaping using view()
reshaped_x = x.view(3, 2)  # Reshaping to a 3x2 tensor
print("Reshaped tensor:")
print(reshaped_x)

# Stacking tensors along a new dimension
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
stacked_tensor = torch.stack((tensor1, tensor2))  # Stack along a new dimension (default dim=0)
print("\nStacked tensor:")
print(stacked_tensor)

# Squeezing and unsqueezing tensors
tensor = torch.tensor([[1], [2], [3]])  # A tensor with shape (3, 1)
squeezed_tensor = tensor.squeeze()  # Squeezing the tensor to shape (3,)
unsqueezed_tensor = tensor.unsqueeze(1)  # Unsqueezing to shape (3, 1,)
print("\nSqueezed tensor:")
print(squeezed_tensor)
print("\nUnsqueezed tensor:")
print(unsqueezed_tensor)

# Permuting dimensions of a tensor
tensor = torch.randn(2, 3, 4)  # A tensor with shape (2, 3, 4)
permuted_tensor = tensor.permute(2, 0, 1)  # Change the order of dimensions to (4, 2, 3)
print("\nPermuted tensor:")
print(permuted_tensor)

# Indexing tensors
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing specific elements
print("\nAccessing specific elements:")
print(tensor[0, 1])  # Accessing element at row 0, column 1

# Slicing tensors
print("\nSlicing tensors:")
print(tensor[:, 1])  # Accessing the second column of the tensor
print(tensor[1:, :2])  # Accessing a slice of the tensor from row 1 onwards and up to column 2


Reshaped tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Stacked tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Squeezed tensor:
tensor([1, 2, 3])

Unsqueezed tensor:
tensor([[[1]],

        [[2]],

        [[3]]])

Permuted tensor:
tensor([[[-0.1259,  0.4105,  0.0756],
         [-1.1247,  0.6839, -0.8160]],

        [[-0.9578,  1.7675, -0.1525],
         [-0.3144,  1.6132,  1.1565]],

        [[ 1.7518, -0.0832,  0.1958],
         [ 0.6260,  0.9332, -1.2107]],

        [[ 0.9796,  0.5087, -1.5688],
         [ 0.0908, -0.9772,  0.5071]]])

Accessing specific elements:
tensor(2)

Slicing tensors:
tensor([2, 5, 8])
tensor([[4, 5],
        [7, 8]])


In [9]:
import numpy as np
import torch

# Create a NumPy array
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])

# Convert NumPy array to PyTorch tensor
pytorch_tensor = torch.from_numpy(numpy_array)
print("PyTorch Tensor:")
print(pytorch_tensor)

# Convert PyTorch tensor to NumPy array
numpy_array_back = pytorch_tensor.numpy()
print("\nNumPy Array:")
print(numpy_array_back)

# Create a random tensor with shape 7x7
random_tensor = torch.randn(7, 7)
print("\nRandom Tensor:")
print(random_tensor)

# Create the tensors
tensor_7x7 = torch.randn(7, 7)
tensor_1x7 = torch.randn(1, 7)

# Transpose the 1x7 tensor to make it 7x1
tensor_7x1 = tensor_1x7.t()

# matrix multiplication
result = torch.matmul(tensor_7x7, tensor_7x1)
print("\nMatrix Multiplication Result:")
print(result)

# matrix multiplication again
result = torch.matmul(tensor_7x7, tensor_7x1)
print("\nMatrix Multiplication Result:")
print(result)

PyTorch Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

NumPy Array:
[[1 2 3]
 [4 5 6]]

Random Tensor:
tensor([[ 1.3272,  0.1106,  0.3374, -0.3201,  0.5689,  0.1333,  0.5600],
        [-0.7351,  0.2755, -0.9336, -0.1527, -0.5300,  1.4535, -1.5414],
        [-0.3315,  0.5505,  0.8885, -1.4867, -0.8898,  0.9005,  0.2615],
        [-0.1494,  1.1523, -1.1309, -0.5415, -0.1605,  0.9327,  0.0649],
        [ 0.0676, -0.5489, -0.4120,  0.0539, -0.0642, -0.7201, -0.6052],
        [-0.6239, -0.4703, -0.8482,  0.8185,  0.2061,  0.7011, -1.0268],
        [ 0.3708, -0.9329,  0.3073,  0.7593,  1.5333, -0.7755, -2.1510]])

Matrix Multiplication Result:
tensor([[-2.4676],
        [ 0.0702],
        [ 1.1727],
        [ 0.7252],
        [-1.4546],
        [-0.8455],
        [ 1.2924]])

Matrix Multiplication Result:
tensor([[-2.4676],
        [ 0.0702],
        [ 1.1727],
        [ 0.7252],
        [-1.4546],
        [-0.8455],
        [ 1.2924]])


In [10]:
import torch

# Create random tensors on CPU
tensor1 = torch.randn(2, 3)
tensor2 = torch.randn(2, 3)

# Check if GPU (CUDA) is available
if torch.cuda.is_available():
    # Move tensors to the GPU
    tensor1 = tensor1.to('cuda')
    tensor2 = tensor2.to('cuda')
    print("Tensors moved to GPU")

    # Verify their device
    print(f"Tensor 1 device: {tensor1.device}")
    print(f"Tensor 2 device: {tensor2.device}")
else:
    print("CUDA not available, tensors remain on CPU")

# matrix multiplication
result = torch.matmul(tensor1, tensor2.t())  # Transposing tensor2 for matrix multiplication

# Find max and min values of the output
max_value = torch.max(result)
min_value = torch.min(result)
print(f"Max value: {max_value}, Min value: {min_value}")

# Find indices of max and min values
max_indices = torch.argmax(result)
min_indices = torch.argmin(result)
print(f"Index of Max value: {max_indices}, Index of Min value: {min_indices}")


CUDA not available, tensors remain on CPU
Max value: 3.6446805000305176, Min value: -2.023585796356201
Index of Max value: 3, Index of Min value: 2


In [11]:
import torch

# Setting seed for reproducibility
torch.manual_seed(7)

# Creating a random tensor with shape (1, 1, 1, 10)
tensor_1 = torch.randn(1, 1, 1, 10)

# Removing dimensions with size 1
tensor_2 = tensor_1.squeeze()

#first tensor and its shape
print("Tensor 1:")
print(tensor_1)
print(f"Tensor 1 shape: {tensor_1.shape}")

# second tensor and its shape
print("\nTensor 2:")
print(tensor_2)
print(f"Tensor 2 shape: {tensor_2.shape}")


Tensor 1:
tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])
Tensor 1 shape: torch.Size([1, 1, 1, 10])

Tensor 2:
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822])
Tensor 2 shape: torch.Size([10])
